chore: update repo
deepin-community/golang-github-rogpeppe-go-internal pull request #1
Opened 2023-08-20 06:18 UTC by chenchongbiao

update version to 1.11.0-1

Log: update repo

2023-08-20 06:29 UTC, chenchongbiao commented
@Zeno-sole @xzl01 @UTsweetyfish

2023-08-21 01:44 UTC, UTsweetyfish requested changes
![image](https://github.com/deepin-community/golang-github-rogpeppe-go-internal/assets/124018391/2d5b6585-072f-4025-83ff-1d58b01186db)

2023-08-21 02:38 UTC, Zeno-sole commented
> ![image](https://user-images.githubusercontent.com/124018391/261891684-2d5b6585-072f-4025-83ff-1d58b01186db.png)

![image](https://github.com/deepin-community/golang-github-rogpeppe-go-internal/assets/43427321/651b23b3-6e44-456e-95d5-b4721fd57803)

2023-08-21 02:38 UTC, Zeno-sole commented
/check obs

2023-08-21 02:41 UTC, Zeno-sole commented
/approve

2023-08-21 02:42 UTC, merged